# Generated by Django 5.1.2 on 2024-10-16 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rule_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="ast_json",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(fields=["name"], name="rule_engine_name_68137c_idx"),
        ),
    ]
